# python异常处理 Exception

### 错误 Error

可能是笔误，也可能是逻辑错误。错误是可以避免的

### 异常 Exception

是意外情况。

不是系统内部的错误，不可控的外部意外，往往不可避免

#### 异常处理

异常如果不处理，会导致当前线程挂掉。最严重后果会导致进程的非正常退出

异常可手动产生raise，也可能是由一些操作产生

##### 捕获异常

~~~python
try: # 有的语言如js为try catch
    1/0
except:
    pass# 处理异常
# 函数内部抓异常，函数中剩余的语句继续执行
# 函数外抓异常， 函数中异常以后的语句不执行
def foo(x:int)->int:# :int 参数类型注解3.5后，->int,返回值类型注解 3.6后新增y:int = 100变量类型注解。
    print("====")
    try:
        print(1/x)
        print('+++++++++')# 这个语句不会被执行，try后发生异常会直接跳转到except语句
    except:
        print('异常')
    print("----------")
    return 0
#############################
def foo(x:int)->int:
    print("====")
#     try:
#         print(1/x)
#     except:
#         print('异常')
    1/x
    print("----------")
    return 0
try:
    foo(0)# 函数外捕获异常将会导致函数中异常后的语句不执行
except:
    print("Eception")
# 异常的嵌套，就不会有异常的发生，因为最里边的异常已经被捕获，没有异常了
~~~

- 捕获特定类型异常，执行需要在except后加上异常类型。一般都需要根据异常类型捕获异常
- 使用缺省异常捕获能捕获所有异常，不建议使用

##### 异常类型及继承层次

~~~ python
# Python异常的继承
BaseException # 异常的根基类
 +-- SystemExit # 模块sys下 sys.exit(1),程序在此以参数为退出码 退出，并引起该异常
 +-- KeyboardInterrupt # ctrl c，在终端/控制台，shell环境下使用该快捷键会终端程序运型并引起异常 
 +-- GeneratorExit
 +-- Exception # 是所有内建的、非系统退出的异常的基类，自定义异常类应该继承自它
     +-- RuntimeError
     |   +-- RecursionError
     +-- MemoryError
     +-- NameError
     +-- StopIteration
     +-- StopAsyncIteration
     +-- ArithmeticError
     |   +-- FloatingPointError
     |   +-- OverflowError
     |   +-- ZeroDivisionError
     +-- LookupError
     |   +-- IndexError
     |   +-- KeyError
     +-- SyntaxError # 语法错误 不是异常 在编译时就出错了
     +-- OSError
     |   +-- BlockingIOError
     |   +-- ChildProcessError
     |   +-- ConnectionError
     |   |   +-- BrokenPipeError
     |   |   +-- ConnectionAbortedError
     |   |   +-- ConnectionRefusedError
     |   |   +-- ConnectionResetError
     |   +-- FileExistsError
     |   +-- FileNotFoundError
     |   +-- InterruptedError
     |   +-- IsADirectoryError
     |   +-- NotADirectoryError
     |   +-- PermissionError
     |   +-- ProcessLookupError
     |   +-- TimeoutError
#####################################
# except 类似于if分支 条件判断为isinstance(异常类), 所以能多条except语句判断
# 没有父子关系的，顺序随便
# 有父子关系的， 子类在前， 父类在后
# 从具体的异常类型到宽泛的异常类型（父类）
# isinstance(True, int)#说明一个类的实例，在isinstance中与其父类，祖宗类等都是true，属于父类类型

~~~

##### raise

raise用来抛出异常

~~~python
class MyException(Exception):
    pass# 不重写init 继承自父类__init__(self, *args, **kwargs): pass
        # 接受的参数为异常描述信息，可以有也可以没有

try:
    raise 1# 在py中不可行，raise后至少为BaseError或其子孙类的实例，一般为Exception及其子类的实例(内建异常，自定义异常)
    raise MyException # 相当于 raise MyException()
    raise MyException('我自定义的异常')
    # raise 会自动调用后变类型的__init__()初始化方法。所有如有重写父类的init函数应该注意参数的改变

except MyException:
    print('自定义异常')
except ZeroDivisionError:# 因为这是算数异常的子类因该放在前边
    print('除0异常')
except ArithmeticError:
    print('算数异常')
except Exception as e:# 给捕获的异常取别名，可以通过别名知道异常类型，异常描述信息等等
    print("异常---", type(e), e.args)# e.args返回一个元组
except:# 缺省捕获所有异常，兜底使用
    pass

~~~



